name: Nutshell integration

on: [push, pull_request]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and start mint
        run: |
          docker run -d -p 8080:8080 --name nutshell -e MINT_LIGHTNING_BACKEND=FakeWallet -e MINT_INPUT_FEE_PPK=0 -e MINT_LISTEN_HOST=0.0.0.0 -e MINT_LISTEN_PORT=8080 -e MINT_PRIVATE_KEY=TEST_PRIVATE_KEY cashubtc/nutshell:0.16.5 poetry run mint

      - name: Check running containers
        run: docker ps

      # - name: Sleep 5 seconds and curl on localhost:3338/v1/info
      #   run: |
      #     sleep 5
      #     curl localhost:3338/v1/info


      - uses: actions/checkout@v4
      # Setup golang
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'
          cache-dependency-path: subdir/go.sum

      - name: Go Toolchain info
        run: |
          go version

      - name: Install dependencies
        run: go get -t ./... 

      - name: Build
        run: |
          go build -v ./...
      - name: run integrations
        run: |
          go test -v ./test/integrations/...
